language: scala
scala:
   - 2.11.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - sudo gem install --user-install executable-hooks
  - wget http://www.us.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar xfz thrift-0.9.3.tar.gz
  - cd thrift-0.9.3 && ./configure && sudo make install
